# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sys_monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sys_monitor.proto\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x07RAMinfo\x12\r\n\x05total\x18\x01 \x01(\x02\x12\x0c\n\x04used\x18\x02 \x01(\x02\x12\x0c\n\x04\x66ree\x18\x03 \x01(\x02\"\x1a\n\x07\x43PUFreq\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x02\"5\n\x08\x44ISkinfo\x12\r\n\x05total\x18\x01 \x01(\x02\x12\x0c\n\x04used\x18\x02 \x01(\x02\x12\x0c\n\x04\x66ree\x18\x03 \x01(\x02\x32\xaa\x01\n\rSystemMonitor\x12\x31\n\x0bgetRAMUsage\x12\x16.google.protobuf.Empty\x1a\x08.RAMinfo\"\x00\x12\x31\n\x0bgetCPUUsage\x12\x16.google.protobuf.Empty\x1a\x08.CPUFreq\"\x00\x12\x33\n\x0cgetDISkUsage\x12\x16.google.protobuf.Empty\x1a\t.DISkinfo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sys_monitor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RAMINFO']._serialized_start=50
  _globals['_RAMINFO']._serialized_end=102
  _globals['_CPUFREQ']._serialized_start=104
  _globals['_CPUFREQ']._serialized_end=130
  _globals['_DISKINFO']._serialized_start=132
  _globals['_DISKINFO']._serialized_end=185
  _globals['_SYSTEMMONITOR']._serialized_start=188
  _globals['_SYSTEMMONITOR']._serialized_end=358
# @@protoc_insertion_point(module_scope)
